// Hunt N' Hire Master Jobs Database
// Auto-generated from spreadsheet

const JOBS_DATA = [
  {
    "id": 1,
    "company": "CNX",
    "publicCompany": "Multinational BPO & Customer Experience Leader",
    "language": "English",
    "status": "active",
    "title": "Customer Service",
    "salary": "20000.0",
    "salaryDisplay": "EGP 20,000",
    "salaryMin": 20000.0,
    "salaryMax": 20000.0,
    "education": "Graduates Only",
    "maxAge": "40.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "Maadi Tech Park / Smart Village",
    "interviewType": "On-Site (Mon–Fri)",
    "interviewDays": "Mon–Fri 11AM–3PM",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Full Name, Phone, Alt Phone, Email",
    "commission": "After 1 Month",
    "notes": "Do NOT share CNX name in posts. No disabilities. Cairo residents preferred (excl. Rehab/Madinaty area)"
  },
  {
    "id": 2,
    "company": "Centro",
    "publicCompany": "Premium Healthcare & BPO Services Partner",
    "language": "Spanish B2 and English B2",
    "status": "active",
    "title": "Centro Spanish Bilingual Account (Medical Account)",
    "salary": "Gross Salary: Up to 31,000 EGP              Overnight Allowance: 1,000 EGP",
    "salaryDisplay": "EGP 31,000",
    "salaryMin": 31000.0,
    "salaryMax": 31000.0,
    "education": "Graduates only",
    "maxAge": "Maximum 40 years old",
    "gender": "Any",
    "experience": "No experience needed (Fresh graduates welcome) 🌟",
    "location": "Maadi 📍",
    "interviewType": "Onsite Interview",
    "interviewDays": "Online Interviews",
    "shift": "Rotational Shifts 🕒",
    "transportation": "Provided 🚌",
    "insurance": "Medical & Social Insurance, Paid Training",
    "workType": "On-Site",
    "foreigners": "no",
    "candidateInfo": "Validation Voice Note (VN)   Online interview within 48 hours",
    "commission": "TBD",
    "notes": "Stable Work Environment, Career Growth Opportunities 🎁"
  },
  {
    "id": 3,
    "company": "Dail Expert",
    "publicCompany": "Premier Financial Sales Agency",
    "language": "English",
    "status": "active",
    "title": "Remote Sales Closer – Debt Settlement ( Full-time)",
    "salary": "18000.0",
    "salaryDisplay": "EGP 18,000",
    "salaryMin": 18000.0,
    "salaryMax": 18000.0,
    "education": "Grads & Undergrads",
    "maxAge": "any",
    "gender": "any",
    "experience": "Not Required",
    "location": "Remote",
    "interviewType": "Online (Mon–Fri)",
    "interviewDays": "Online (Mon–Fri)",
    "shift": "Mon–Fri 6PM–3AM Cairo Time (Full Time)",
    "transportation": "Not Required (Remote)",
    "insurance": "Not Specified",
    "workType": "Hybrid",
    "foreigners": "Yes",
    "candidateInfo": "https://apply.dialexpert.com/apply?ref=hunt-n'-hire",
    "commission": "17 to 25 days",
    "notes": "PC + stable internet + headset required. B2 English (near-native). Full time 18K Net + $20/deal + bonuses."
  },
  {
    "id": 4,
    "company": "Dail Expert",
    "publicCompany": "Premier Financial Sales Agency",
    "language": "English",
    "status": "active",
    "title": "Remote Sales Closer – Debt Settlement (part time)",
    "salary": "7000.0",
    "salaryDisplay": "EGP 7,000",
    "salaryMin": 7000.0,
    "salaryMax": 7000.0,
    "education": "Grads & Undergrads",
    "maxAge": "any",
    "gender": "any",
    "experience": "Not Required",
    "location": "Remote",
    "interviewType": "Online (Mon–Fri)",
    "interviewDays": "Online (Mon–Fri)",
    "shift": "Mon–Fri from 5PM Cairo Time (Part Time)",
    "transportation": "Not Required (Remote)",
    "insurance": "Not Specified",
    "workType": "Hybrid",
    "foreigners": "Yes",
    "candidateInfo": "https://apply.dialexpert.com/apply?ref=hunt-n'-hire",
    "commission": "17 to 25 days",
    "notes": "PC + stable internet + headset required. B2 English (near-native). Part time 7K Net."
  },
  {
    "id": 5,
    "company": "LTS",
    "publicCompany": "Hospitality & Survey Solutions Provider",
    "language": "English",
    "status": "active",
    "title": "Hotel Survey Specialist – USA Account",
    "salary": "14000.0",
    "salaryDisplay": "EGP 14,000",
    "salaryMin": 14000.0,
    "salaryMax": 14000.0,
    "education": "Grads & Undergrads",
    "maxAge": "35.0",
    "gender": "Any",
    "experience": "Not Required (CS plus)",
    "location": "Sheraton / New Cairo",
    "interviewType": "On-Site (Mon–Fri 4PM–7PM)",
    "interviewDays": "Mon–Fri 4PM–7PM",
    "shift": "Afternoon/Night (3PM–2AM rotational)",
    "transportation": "Females Only",
    "insurance": "Medical & Social (after 3m)",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Date, Time, Name, Phone, ID, Email, Grad Status, Notice Period, Experience",
    "commission": "After 1 Month",
    "notes": "Age 18–35 strictly. Insurance after 3 months."
  },
  {
    "id": 6,
    "company": "Sutherland",
    "publicCompany": "Global Technology & Digital Support Partner",
    "language": "English",
    "status": "active",
    "title": "Customer Service",
    "salary": "17300.0",
    "salaryDisplay": "EGP 17,300",
    "salaryMin": 17300.0,
    "salaryMax": 17300.0,
    "education": "Grads & Undergrads",
    "maxAge": "40.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "New Cairo, 5th Settlement",
    "interviewType": "On-Site (Mon–Fri 7PM–11PM)",
    "interviewDays": "Mon–Fri 7PM–11PM",
    "shift": "Rotational (12PM–9AM)",
    "transportation": "Provided (select points)",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Name, Phone, Graduation Status, Email",
    "commission": "After 1 Month",
    "notes": "Full salary for first 3 months. Night interviews."
  },
  {
    "id": 7,
    "company": "TP",
    "publicCompany": "Global Customer Experience Giant",
    "language": "English",
    "status": "active",
    "title": "Customer Service",
    "salary": "19000.0",
    "salaryDisplay": "EGP 19,000",
    "salaryMin": 19000.0,
    "salaryMax": 19000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "5th Settlement, New Cairo",
    "interviewType": "On-Site @ TP Plaza",
    "interviewDays": "Daily",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "10% raise after 6m, KPIs in EUR"
  },
  {
    "id": 8,
    "company": "TTC",
    "publicCompany": "Top Tier Telesales & Marketing Group",
    "language": "English",
    "status": "active",
    "title": "Telesales – US & UK Accounts",
    "salary": "12000.0",
    "salaryDisplay": "EGP 12,000",
    "salaryMin": 12000.0,
    "salaryMax": 12000.0,
    "education": "Grads & Undergrads",
    "maxAge": "28.0",
    "gender": "Any",
    "experience": "Not Required (plus)",
    "location": "Nasr City",
    "interviewType": "On-Site (Mon–Fri 3PM–11PM)",
    "interviewDays": "Mon–Fri 3PM–11PM",
    "shift": "US: 3PM–11PM / UK: 12PM–8PM",
    "transportation": "US Account Only (females door-to-door)",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Date, Name, Phone, Age, Shift, Graduation Status",
    "commission": "50% after test call + 50% after 1 month",
    "notes": "Sat & Sun off. Age 18–28."
  },
  {
    "id": 9,
    "company": "TTEC",
    "publicCompany": "Global BPO & Tech Support Specialist",
    "language": "French",
    "status": "active",
    "title": "Customer Service – Bilingual",
    "salary": "30700.0",
    "salaryDisplay": "EGP 30,700",
    "salaryMin": 30700.0,
    "salaryMax": 30700.0,
    "education": "Grads & Dropouts",
    "maxAge": "55.0",
    "gender": "Any",
    "experience": "Preferred (CS)",
    "location": "Maadi Tech Park",
    "interviewType": "On-Site (Mon–Fri 11AM–5PM)",
    "interviewDays": "Mon–Fri 11AM–5PM",
    "shift": "Rotational 24/7 (from 8AM)",
    "transportation": "Provided (door-to-door females after 10PM)",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Date, Name, Phone, ID, Email",
    "commission": "After 1 Month",
    "notes": "Max age 55 – most relaxed age requirement."
  },
  {
    "id": 10,
    "company": "e&",
    "publicCompany": "Major Telecommunications Group",
    "language": "English",
    "status": "active",
    "title": "Tech Support – Outbound (TS ENG Account)",
    "salary": "15887.0",
    "salaryDisplay": "EGP 15,887",
    "salaryMin": 15887.0,
    "salaryMax": 15887.0,
    "education": "Graduates Only",
    "maxAge": "32.0",
    "gender": "males and females",
    "experience": "Not Required",
    "location": "Maadi (Degla)",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Fixed Morning (7AM–4PM)",
    "transportation": "Not Provided",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, English Level, Account, Email",
    "commission": "After 1 Month",
    "notes": ""
  },
  {
    "id": 11,
    "company": "e&",
    "publicCompany": "Major Telecommunications Group",
    "language": "English",
    "status": "active",
    "title": "Customer Service – Inbound (101 Account)",
    "salary": "13500.0",
    "salaryDisplay": "EGP 13,500",
    "salaryMin": 13500.0,
    "salaryMax": 13500.0,
    "education": "Graduates Only",
    "maxAge": "32.0",
    "gender": "Males Only",
    "experience": "Not Required",
    "location": "Maadi (Degla)",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "Not Provided",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, English Level, Account, Email",
    "commission": "After 1 Month",
    "notes": "Males only. Age strict (below 32)."
  },
  {
    "id": 12,
    "company": "e&",
    "publicCompany": "Major Telecommunications Group",
    "language": "English",
    "status": "active",
    "title": "Chat Support (Smiles Account)",
    "salary": "12374.0",
    "salaryDisplay": "EGP 12,374",
    "salaryMin": 12374.0,
    "salaryMax": 12374.0,
    "education": "Graduates Only",
    "maxAge": "32.0",
    "gender": "Males Only",
    "experience": "Not Required",
    "location": "Maadi (Degla)",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "Not Provided",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, English Level, Account, Email",
    "commission": "After 1 Month",
    "notes": ""
  },
  {
    "id": 13,
    "company": "e&",
    "publicCompany": "Major Telecommunications Group",
    "language": "English",
    "status": "active",
    "title": "SMB",
    "salary": "13,254 EGP + 2,633 Variable + 3,113 complexity allowance",
    "salaryDisplay": "EGP 3,113 - 13,254",
    "salaryMin": 3113.0,
    "salaryMax": 13254.0,
    "education": "Graduates Only",
    "maxAge": "32.0",
    "gender": "Males Only",
    "experience": "Not Required",
    "location": "Maadi (Degla)",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "Not Provided",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, English Level, Account, Email",
    "commission": "After 1 Month",
    "notes": "Sales commission up to 700 Dirhams monthly"
  },
  {
    "id": 14,
    "company": "e&",
    "publicCompany": "Major Telecommunications Group",
    "language": "English",
    "status": "active",
    "title": "e&money B1",
    "salary": "12,000 EGP",
    "salaryDisplay": "EGP 12,000",
    "salaryMin": 12000.0,
    "salaryMax": 12000.0,
    "education": "Graduates Only",
    "maxAge": "32.0",
    "gender": "Males Only",
    "experience": "Not Required",
    "location": "Maadi (Degla)",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "Not Provided",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, English Level, Account, Email",
    "commission": "After 1 Month",
    "notes": ""
  },
  {
    "id": 15,
    "company": "e&",
    "publicCompany": "Major Telecommunications Group",
    "language": "English",
    "status": "active",
    "title": "Retention",
    "salary": "12,136 EGP + 2,364 Variable",
    "salaryDisplay": "EGP 12,136",
    "salaryMin": 12136.0,
    "salaryMax": 12136.0,
    "education": "Graduates Only",
    "maxAge": "32.0",
    "gender": "Males Only",
    "experience": "Not Required",
    "location": "Maadi (Degla)",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "Not Provided",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, English Level, Account, Email",
    "commission": "After 1 Month",
    "notes": ""
  },
  {
    "id": 16,
    "company": "eClerx",
    "publicCompany": "Premium Business Operations & IT Partner",
    "language": "English",
    "status": "active",
    "title": "Customer Support  – Comcast acc",
    "salary": "18000 to 20K",
    "salaryDisplay": "EGP 18,000 - 20,000",
    "salaryMin": 18000.0,
    "salaryMax": 20000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "6 Month at least",
    "location": "Maadi Tech Park",
    "interviewType": "On-Site (Sun–Thu 12PM–4:45PM)",
    "interviewDays": "Sun–Thu, slots every 15 mins",
    "shift": "Rotational (incl. evenings/weekends)",
    "transportation": "Not Specified",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email",
    "commission": "After 1 Month",
    "notes": "Performance bonus up to 48K annually. 2 on-site assessments (~1.5hrs each)."
  },
  {
    "id": 17,
    "company": "eClerx",
    "publicCompany": "Premium Business Operations & IT Partner",
    "language": "English",
    "status": "active",
    "title": "Technical Support  acc",
    "salary": "18000 to 20K",
    "salaryDisplay": "EGP 18,000 - 20,000",
    "salaryMin": 18000.0,
    "salaryMax": 20000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "1 yr Technical Support exp Mandatory.",
    "location": "Maadi Tech Park",
    "interviewType": "On-Site (Sun–Thu 12PM–4:45PM)",
    "interviewDays": "Sun–Thu, slots every 15 mins",
    "shift": "Rotational (incl. evenings/weekends)",
    "transportation": "Not Specified",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email",
    "commission": "After 1 Month",
    "notes": "Performance bonus up to 48K annually. 2 on-site assessments (~1.5hrs each)."
  },
  {
    "id": 18,
    "company": "Atain",
    "publicCompany": "European Language Support & Customer Care Hub",
    "language": "German Bilingual B2",
    "status": "on hold",
    "title": "Bilingual Customer Service Representative",
    "salary": "31,400 EGP Net",
    "salaryDisplay": "EGP 31,400",
    "salaryMin": 31400.0,
    "salaryMax": 31400.0,
    "education": "University Graduates",
    "maxAge": "Max age 40",
    "gender": "Any",
    "experience": "Previous Customer Service / Contact Center experience is required",
    "location": "Maadi Technology Park (Work from site)",
    "interviewType": "On-site Interview",
    "interviewDays": "Monday to Friday, 11:00 AM to 4:00 PM",
    "shift": "Rotational Shifts",
    "transportation": "Transportation provided after 9:00 PM. Meeting points available, with door-to-door transportation for ladies after 9:00 PM.",
    "insurance": "Medical & Social Insurance included",
    "workType": "On-Site",
    "foreigners": "Egyptian Nationals",
    "candidateInfo": "",
    "commission": "30 days",
    "notes": "Joining Date: 18 September 2026"
  },
  {
    "id": 19,
    "company": "Atain",
    "publicCompany": "European Language Support & Customer Care Hub",
    "language": "German Monolingual B2",
    "status": "on hold",
    "title": "Customer Service Representative",
    "salary": "30,000 EGP Net",
    "salaryDisplay": "EGP 30,000",
    "salaryMin": 30000.0,
    "salaryMax": 30000.0,
    "education": "University Graduates",
    "maxAge": "Max age 40",
    "gender": "Any",
    "experience": "No experience required",
    "location": "Maadi Technology Park (Work from site)",
    "interviewType": "On-site Interview",
    "interviewDays": "Monday to Friday, 11:00 AM to 4:00 PM",
    "shift": "Rotational Shifts",
    "transportation": "Transportation provided after 9:00 PM. Meeting points available, with door-to-door transportation for ladies after 9:00 PM.",
    "insurance": "Medical & Social Insurance included",
    "workType": "On-Site",
    "foreigners": "Egyptian Nationals",
    "candidateInfo": "",
    "commission": "30 days",
    "notes": "Joining Dates: 31 July 2026, 04 September 2026"
  },
  {
    "id": 20,
    "company": "Atain",
    "publicCompany": "European Language Support & Customer Care Hub",
    "language": "Spanish Monolingual   B2+/C1",
    "status": "on hold",
    "title": "Customer Service Representative",
    "salary": "22,900 EGP Net + Unlimited Retention Bonus in EUR",
    "salaryDisplay": "EGP 22,900",
    "salaryMin": 22900.0,
    "salaryMax": 22900.0,
    "education": "Graduates only",
    "maxAge": "Max age 40",
    "gender": "Any",
    "experience": "Ready to start immediately",
    "location": "Maadi (Work from site)",
    "interviewType": "Online Interview",
    "interviewDays": "Monday to Friday, 10:00 AM to 8:00 PM",
    "shift": "Rotational Shifts",
    "transportation": "Available starting at 9:00 PM",
    "insurance": "Medical & Social Insurance included",
    "workType": "On-Site",
    "foreigners": "Egyptians only",
    "candidateInfo": "",
    "commission": "30 days",
    "notes": "1st floor, Vodafone building, Maadi Technology Park, Al Lasilki, Ezbet Fahmy, Maadi, Cairo Governorate.      Candidates must send 2 voice notes introducing themselves."
  },
  {
    "id": 21,
    "company": "Atain",
    "publicCompany": "European Language Support & Customer Care Hub",
    "language": "Italian Bilingual B2",
    "status": "on hold",
    "title": "Bilingual Customer Service Representative",
    "salary": "22,280 EGP Net",
    "salaryDisplay": "EGP 22,280",
    "salaryMin": 22280.0,
    "salaryMax": 22280.0,
    "education": "University Graduates",
    "maxAge": "Max age 40",
    "gender": "Any",
    "experience": "Previous Customer Service / Contact Center experience is required.",
    "location": "Maadi Technology Park (Work from site)",
    "interviewType": "On-site Interview",
    "interviewDays": "Monday to Friday, 11:00 AM to 4:00 PM",
    "shift": "Rotational Shifts",
    "transportation": "Transportation provided after 9:00 PM. Meeting points available, with door-to-door transportation for ladies after 9:00 PM.",
    "insurance": "Medical & Social Insurance included",
    "workType": "On-Site",
    "foreigners": "Egyptian Nationals",
    "candidateInfo": "",
    "commission": "30 days",
    "notes": "Joining Dates: 31 July 2026, 18 September 2026"
  },
  {
    "id": 22,
    "company": "Atain",
    "publicCompany": "European Language Support & Customer Care Hub",
    "language": "French Bilingual      B2+/C1",
    "status": "on hold",
    "title": "Bilingual Customer Service Representative",
    "salary": "Up to 30,000 EGP (Based on account)",
    "salaryDisplay": "EGP 30,000",
    "salaryMin": 30000.0,
    "salaryMax": 30000.0,
    "education": "Graduates only",
    "maxAge": "Max age 40",
    "gender": "Any",
    "experience": "Minimum 6 months of experience in GDS (Amadeus)",
    "location": "Maadi (Work from site)",
    "interviewType": "On-site Interview",
    "interviewDays": "Monday to Friday, 11:00 AM to 4:00 PM",
    "shift": "Rotational Shifts",
    "transportation": "Available starting at 9:00 PM",
    "insurance": "Medical & Social Insurance included",
    "workType": "On-Site",
    "foreigners": "Egyptians only",
    "candidateInfo": "",
    "commission": "30 days",
    "notes": "1st floor, Vodafone building, Maadi Technology Park, Al Lasilki, Ezbet Fahmy, Maadi, Cairo Governorate.    Candidates must send 2 voice notes introducing themselves."
  },
  {
    "id": 23,
    "company": "CAIZO",
    "publicCompany": "Leading Fast-Casual Restaurant Chain",
    "language": "Arabic",
    "status": "on hold",
    "title": "Supervisor / Asst. Manager / Manager",
    "salary": "15000.0",
    "salaryDisplay": "EGP 15,000",
    "salaryMin": 15000.0,
    "salaryMax": 15000.0,
    "education": "Experience Required",
    "maxAge": "45.0",
    "gender": "Males Only",
    "experience": "Required (F&B)",
    "location": "Multiple Branches",
    "interviewType": "On-Site (Mon–Thu 2PM–6PM)",
    "interviewDays": "Mon–Thu 2PM–6PM",
    "shift": "Shift Work",
    "transportation": "Not Specified",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "CV, ID photo, Experience details",
    "commission": "After 1 Month",
    "notes": "F&B management roles. Military service completed required."
  },
  {
    "id": 24,
    "company": "CAIZO",
    "publicCompany": "Leading Fast-Casual Restaurant Chain",
    "language": "Arabic",
    "status": "on hold",
    "title": "Student Crew (No Exp)",
    "salary": "6500.0",
    "salaryDisplay": "EGP 6,500",
    "salaryMin": 6500.0,
    "salaryMax": 6500.0,
    "education": "No Requirement",
    "maxAge": "35.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "Multiple Branches",
    "interviewType": "On-Site (Mon–Thu 2PM–6PM)",
    "interviewDays": "Mon–Thu 2PM–6PM",
    "shift": "Shift Work",
    "transportation": "Not Specified",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "CV, ID photo",
    "commission": "After 1 Month",
    "notes": "F&B sector. Fast promotion. Gulf opportunity after 1 year"
  },
  {
    "id": 25,
    "company": "CNX",
    "publicCompany": "Multinational BPO & Customer Experience Leader",
    "language": "German",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "38000.0",
    "salaryDisplay": "EGP 38,000",
    "salaryMin": 38000.0,
    "salaryMax": 38000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "Smart Village",
    "interviewType": "On-Site (Mon–Fri)",
    "interviewDays": "Mon–Fri 11AM–3PM @ Smart Village",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "Yes (valid visa 3m+)",
    "candidateInfo": "Full Name, Phone, Alt Phone, Email",
    "commission": "After 1 Month",
    "notes": "Do NOT share CNX name in posts. Cairo residents preferred"
  },
  {
    "id": 26,
    "company": "CNX",
    "publicCompany": "Multinational BPO & Customer Experience Leader",
    "language": "French",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "27000.0",
    "salaryDisplay": "EGP 27,000",
    "salaryMin": 27000.0,
    "salaryMax": 27000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "Smart Village",
    "interviewType": "On-Site (Mon–Fri)",
    "interviewDays": "Mon–Fri 11AM–3PM @ Smart Village",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "Yes (valid visa 3m+)",
    "candidateInfo": "Full Name, Phone, Alt Phone, Email",
    "commission": "After 1 Month",
    "notes": "Do NOT share CNX name in posts. Cairo residents preferred"
  },
  {
    "id": 27,
    "company": "Centro",
    "publicCompany": "Premium Healthcare & BPO Services Partner",
    "language": "English B2",
    "status": "on hold",
    "title": "Centro Appointment Setter Account 📞",
    "salary": "Up to 20,000 EGP",
    "salaryDisplay": "EGP 20,000",
    "salaryMin": 20000.0,
    "salaryMax": 20000.0,
    "education": "Graduates only",
    "maxAge": "Maximum 40 years old",
    "gender": "Any",
    "experience": "Minimum 6 months of Call Center experience (Mandatory)",
    "location": "Maadi 📍",
    "interviewType": "Online Interviews",
    "interviewDays": "Online Interviews",
    "shift": "Fixed Shift (3:00 PM – 12:00 AM) 🕒",
    "transportation": "Provided 🚌",
    "insurance": "Medical & Social Insurance, Paid Training",
    "workType": "On-Site",
    "foreigners": "no",
    "candidateInfo": "Validation Voice Note (VN)   Online interview within 48 hours",
    "commission": "TBD",
    "notes": "Stable Work Environment, Career Growth Opportunities 🎁"
  },
  {
    "id": 28,
    "company": "Enable",
    "publicCompany": "Multinational Technical Support Hub",
    "language": "Dutch",
    "status": "on hold",
    "title": "Customer Service (Monolingual)",
    "salary": "62000.0",
    "salaryDisplay": "EGP 62,000",
    "salaryMin": 62000.0,
    "salaryMax": 62000.0,
    "education": "Grads & Undergrads",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (CS)",
    "location": "Smart Village",
    "interviewType": "Online (Sun–Thu 10AM–4PM)",
    "interviewDays": "Sun–Thu 10AM–4PM",
    "shift": "Rotational (9AM–9PM)",
    "transportation": "Provided",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Age, Grad Status, Nationality, Language, Exp, Level",
    "commission": "After 1 Month",
    "notes": "Only active position in Enable currently"
  },
  {
    "id": 29,
    "company": "Enable",
    "publicCompany": "Multinational Technical Support Hub",
    "language": "Portuguese",
    "status": "on hold",
    "title": "Customer Service (Monolingual)",
    "salary": "42000.0",
    "salaryDisplay": "EGP 42,000",
    "salaryMin": 42000.0,
    "salaryMax": 42000.0,
    "education": "Grads & Undergrads",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (CS)",
    "location": "Smart Village",
    "interviewType": "Online (Sun–Thu 10AM–4PM)",
    "interviewDays": "Sun–Thu 10AM–4PM",
    "shift": "Rotational (9AM–9PM)",
    "transportation": "Provided",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "Yes (valid visa)",
    "candidateInfo": "Interview Date, Name, Phone, Email, Age, Grad Status, Nationality, Language, Exp, Level",
    "commission": "After 1 Month",
    "notes": "On Hold. Min typing 20 WPM"
  },
  {
    "id": 30,
    "company": "Enable",
    "publicCompany": "Multinational Technical Support Hub",
    "language": "German",
    "status": "on hold",
    "title": "Customer Service (Monolingual)",
    "salary": "39200.0",
    "salaryDisplay": "EGP 39,200",
    "salaryMin": 39200.0,
    "salaryMax": 39200.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (CS)",
    "location": "Smart Village",
    "interviewType": "Online (Sun–Thu 10AM–4PM)",
    "interviewDays": "Sun–Thu 10AM–4PM",
    "shift": "Fixed Morning (10AM–7PM)",
    "transportation": "Provided",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Age, Grad Status, Nationality, Language, Exp, Level",
    "commission": "After 1 Month",
    "notes": "On Hold"
  },
  {
    "id": 31,
    "company": "Enable",
    "publicCompany": "Multinational Technical Support Hub",
    "language": "Spanish",
    "status": "on hold",
    "title": "Customer Service (Monolingual)",
    "salary": "38000.0",
    "salaryDisplay": "EGP 38,000",
    "salaryMin": 38000.0,
    "salaryMax": 38000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (CS)",
    "location": "Smart Village",
    "interviewType": "Online (Sun–Thu 10AM–4PM)",
    "interviewDays": "Sun–Thu 10AM–4PM",
    "shift": "Rotational (9AM–9PM)",
    "transportation": "Provided",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "Yes (valid visa)",
    "candidateInfo": "Interview Date, Name, Phone, Email, Age, Grad Status, Nationality, Language, Exp, Level",
    "commission": "After 1 Month",
    "notes": "On Hold"
  },
  {
    "id": 32,
    "company": "Enable",
    "publicCompany": "Multinational Technical Support Hub",
    "language": "French",
    "status": "on hold",
    "title": "Customer Service (Monolingual)",
    "salary": "31500.0",
    "salaryDisplay": "EGP 31,500",
    "salaryMin": 31500.0,
    "salaryMax": 31500.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (CS)",
    "location": "Smart Village",
    "interviewType": "Online (Sun–Thu 10AM–4PM)",
    "interviewDays": "Sun–Thu 10AM–4PM",
    "shift": "Fixed Morning (10AM–7PM)",
    "transportation": "Provided",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Age, Grad Status, Nationality, Language, Exp, Level",
    "commission": "After 1 Month",
    "notes": "On Hold"
  },
  {
    "id": 33,
    "company": "Golf Global",
    "publicCompany": "International Telesales & Outreach Partner",
    "language": "Fluent English (C1 level).",
    "status": "on hold",
    "title": "Full-Time Tele-Sales Agents",
    "salary": "11,000 EGP net base salary + 2,000 EGP KPIs.",
    "salaryDisplay": "EGP 11,000",
    "salaryMin": 11000.0,
    "salaryMax": 11000.0,
    "education": "Graduates and undergraduates are welcomed.",
    "maxAge": "18 to 26 years.",
    "gender": "Any",
    "experience": "No EXP Needed",
    "location": "(Abbasya – Borg Al-Tatbayen, Floor 14)",
    "interviewType": "on-site",
    "interviewDays": "Monday to Friday between 5:00 PM and 8:00 PM.",
    "shift": "Working Hours: 3:30 PM – 11:30 PM (Monday to Friday).",
    "transportation": "Transportation is not provided.",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "Egyptians only.",
    "candidateInfo": "",
    "commission": "TBD",
    "notes": ""
  },
  {
    "id": 34,
    "company": "Golf Global",
    "publicCompany": "International Telesales & Outreach Partner",
    "language": "English fluency at C1 level or higher.",
    "status": "on hold",
    "title": "Part-Time Telesales Representative",
    "salary": "7,000 EGP net base salary.",
    "salaryDisplay": "EGP 7,000",
    "salaryMin": 7000.0,
    "salaryMax": 7000.0,
    "education": "Graduates and undergraduates are welcomed.",
    "maxAge": "18 to 26 years.",
    "gender": "Any",
    "experience": "No EXP Needed",
    "location": "(Abbasya – Borg Al-Tatbayen, Floor 14)",
    "interviewType": "on-site",
    "interviewDays": "Monday to Friday between 5:00 PM and 8:00 PM.",
    "shift": "Working Hours: 3:30 PM – 11:30 PM (Fixed Shift).",
    "transportation": "Transportation is not provided.",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "Egyptians only.",
    "candidateInfo": "",
    "commission": "TBD",
    "notes": "11 days per month on a repeating 4-week rotation (e.g., Week 1: 2 days, Week 2: 3 days, etc.).      Working Days: Monday to Friday (specific days coordinated with the Team Leader)."
  },
  {
    "id": 35,
    "company": "HSBC",
    "publicCompany": "Leading Global Banking & Financial Institution",
    "language": "English",
    "status": "on hold",
    "title": "Customer Service (Banking)",
    "salary": "18404.0",
    "salaryDisplay": "EGP 18,404",
    "salaryMin": 18404.0,
    "salaryMax": 18404.0,
    "education": "University Grads Only",
    "maxAge": "30.0",
    "gender": "Any",
    "experience": "Max 3 Years",
    "location": "Smart Village (Hybrid)",
    "interviewType": "On-Site @ Smart Village",
    "interviewDays": "TBD",
    "shift": "Rotational / Night",
    "transportation": "Provided (night - door to door females)",
    "insurance": "Medical & Social",
    "workType": "Hybrid",
    "foreigners": "No",
    "candidateInfo": "CV, Full Name, Phone, Email",
    "commission": "After 1 Month",
    "notes": "Hybrid model. Training 100% on-site. Institutes grads NOT allowed."
  },
  {
    "id": 36,
    "company": "IGT",
    "publicCompany": "Global Travel & Customer Care Specialist",
    "language": "Dutch",
    "status": "on hold",
    "title": "Customer Service / GDS",
    "salary": "45000.0",
    "salaryDisplay": "EGP 45,000",
    "salaryMin": 45000.0,
    "salaryMax": 45000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (6m+ CS/GDS)",
    "location": "Maadi",
    "interviewType": "On-Site @ IGT Maadi",
    "interviewDays": "TBD",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "Min 6 months CS or GDS exp"
  },
  {
    "id": 37,
    "company": "IGT",
    "publicCompany": "Global Travel & Customer Care Specialist",
    "language": "German",
    "status": "on hold",
    "title": "Customer Service / GDS",
    "salary": "35000.0",
    "salaryDisplay": "EGP 35,000",
    "salaryMin": 35000.0,
    "salaryMax": 35000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (6m+ CS/GDS)",
    "location": "Maadi",
    "interviewType": "On-Site @ IGT Maadi",
    "interviewDays": "TBD",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "Min 6 months CS or GDS exp"
  },
  {
    "id": 38,
    "company": "IGT",
    "publicCompany": "Global Travel & Customer Care Specialist",
    "language": "Portuguese",
    "status": "on hold",
    "title": "Customer Service / GDS",
    "salary": "27600.0",
    "salaryDisplay": "EGP 27,600",
    "salaryMin": 27600.0,
    "salaryMax": 27600.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (6m+ CS/GDS)",
    "location": "Maadi",
    "interviewType": "On-Site @ IGT Maadi",
    "interviewDays": "TBD",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "Min 6 months CS or GDS exp"
  },
  {
    "id": 39,
    "company": "IGT",
    "publicCompany": "Global Travel & Customer Care Specialist",
    "language": "Italian",
    "status": "on hold",
    "title": "Customer Service / GDS",
    "salary": "25000.0",
    "salaryDisplay": "EGP 25,000",
    "salaryMin": 25000.0,
    "salaryMax": 25000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (6m+ CS/GDS)",
    "location": "Maadi",
    "interviewType": "On-Site @ IGT Maadi",
    "interviewDays": "TBD",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "Min 6 months CS or GDS exp"
  },
  {
    "id": 40,
    "company": "IGT",
    "publicCompany": "Global Travel & Customer Care Specialist",
    "language": "French",
    "status": "on hold",
    "title": "Customer Service / GDS",
    "salary": "23000.0",
    "salaryDisplay": "EGP 23,000",
    "salaryMin": 23000.0,
    "salaryMax": 23000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (6m+ CS/GDS)",
    "location": "Maadi",
    "interviewType": "On-Site @ IGT Maadi",
    "interviewDays": "TBD",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "Min 6 months CS or GDS exp"
  },
  {
    "id": 41,
    "company": "IGT",
    "publicCompany": "Global Travel & Customer Care Specialist",
    "language": "Spanish",
    "status": "on hold",
    "title": "Customer Service / GDS",
    "salary": "22000.0",
    "salaryDisplay": "EGP 22,000",
    "salaryMin": 22000.0,
    "salaryMax": 22000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (6m+ CS/GDS)",
    "location": "Maadi",
    "interviewType": "On-Site @ IGT Maadi",
    "interviewDays": "TBD",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "Min 6 months CS or GDS exp"
  },
  {
    "id": 42,
    "company": "IGT",
    "publicCompany": "Global Travel & Customer Care Specialist",
    "language": "English",
    "status": "on hold",
    "title": "Customer Service / GDS",
    "salary": "18000.0",
    "salaryDisplay": "EGP 18,000",
    "salaryMin": 18000.0,
    "salaryMax": 18000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required",
    "location": "Maadi",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "Experience is a MUST"
  },
  {
    "id": 43,
    "company": "Insource",
    "publicCompany": "Corporate Support & Admin Services Partner",
    "language": "English Level C1",
    "status": "on hold",
    "title": "Telesales (USA)",
    "salary": "12,000 EGP Net + Unlimited Commissions",
    "salaryDisplay": "EGP 12,000",
    "salaryMin": 12000.0,
    "salaryMax": 12000.0,
    "education": "raduates & Undergraduates welcome (High school graduates not accepted)",
    "maxAge": "18 to 30 years old",
    "gender": "Any",
    "experience": "Not Required",
    "location": "Nasr City",
    "interviewType": "On-site interview",
    "interviewDays": "from Monday to Friday, 2:00 PM to 4:00 PM",
    "shift": "Males: 3:00 PM – 12:00 AM    Females: 3:00 PM – 11:00 PM     Days Off: Saturday & Sunday",
    "transportation": "Not Provided",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "accepted",
    "candidateInfo": "",
    "commission": "TBD",
    "notes": "Mention recruitment by \"MOSLA Pioneers\" when applying."
  },
  {
    "id": 44,
    "company": "Insource",
    "publicCompany": "Corporate Support & Admin Services Partner",
    "language": "Strong Saudi accent is mandatory (لهجة سعودية قوية)",
    "status": "on hold",
    "title": "Al Jild Al Zahabi – Dentist & Derma Services)",
    "salary": "Salary: 10,000 EGP Basic",
    "salaryDisplay": "EGP 10,000",
    "salaryMin": 10000.0,
    "salaryMax": 10000.0,
    "education": "Undergraduates are preferred",
    "maxAge": "18 to 30 years old",
    "gender": "Females Only",
    "experience": "Not Required",
    "location": "Nasr City",
    "interviewType": "On-site interview",
    "interviewDays": "from Monday to Friday, 2:00 PM to 4:00 PM",
    "shift": "12:00 PM – 9:00 PM   Days Off: Friday",
    "transportation": "Not Provided",
    "insurance": "Not Specified",
    "workType": "On-Site",
    "foreigners": "accepted",
    "candidateInfo": ": Send CV + a short voice note introducing yourself in a Saudi accent.",
    "commission": "TBD",
    "notes": "Mention recruitment by \"MOSLA Pioneers\" when applying."
  },
  {
    "id": 45,
    "company": "Intelcia",
    "publicCompany": "Global CX & Customer Solutions Center",
    "language": "English",
    "status": "on hold",
    "title": "Technical Support – US Accounts",
    "salary": "14000.0",
    "salaryDisplay": "EGP 14,000",
    "salaryMin": 14000.0,
    "salaryMax": 14000.0,
    "education": "Grads & Undergrads",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "Sheikh Zayed, October",
    "interviewType": "Online (Mon–Fri)",
    "interviewDays": "Mon–Fri",
    "shift": "Rotational 24/7 (incl. overnight)",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Phone, ID, Graduation status, Nationality, DOB, Faculty, Address, Email",
    "commission": "After 1 Month",
    "notes": "On Hold. Speech test required first (must score C1)."
  },
  {
    "id": 46,
    "company": "Intouch",
    "publicCompany": "Intouch",
    "language": "French",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "34000.0",
    "salaryDisplay": "EGP 34,000",
    "salaryMin": 34000.0,
    "salaryMax": 34000.0,
    "education": "Graduates Only",
    "maxAge": "Any",
    "gender": "Any",
    "experience": "Required (6m+ CS)",
    "location": "Maadi",
    "interviewType": "Online (Mon–Fri)",
    "interviewDays": "Online (Mon–Fri)",
    "shift": "Rotational",
    "transportation": "Provided (deducted)",
    "insurance": "Social & Medical",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Name, Phone, Experience, Language Level",
    "commission": "After 1 Month",
    "notes": "Transport allowance deducted from salary if used"
  },
  {
    "id": 47,
    "company": "Intouch",
    "publicCompany": "Intouch",
    "language": "Spanish",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "30000.0",
    "salaryDisplay": "EGP 30,000",
    "salaryMin": 30000.0,
    "salaryMax": 30000.0,
    "education": "Graduates Only",
    "maxAge": "Any",
    "gender": "Any",
    "experience": "Required (6m+ CS)",
    "location": "Maadi",
    "interviewType": "Online (Mon–Fri)",
    "interviewDays": "Mon–Fri",
    "shift": "Rotational",
    "transportation": "Provided",
    "insurance": "Social & Medical",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Name, Phone, Experience, Language Level",
    "commission": "After 1 Month",
    "notes": "B2 Spanish & English min"
  },
  {
    "id": 48,
    "company": "Intouch",
    "publicCompany": "Intouch",
    "language": "English",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "21000.0",
    "salaryDisplay": "EGP 21,000",
    "salaryMin": 21000.0,
    "salaryMax": 21000.0,
    "education": "Graduates Only",
    "maxAge": "Any",
    "gender": "Any",
    "experience": "Required (6m+ CS)",
    "location": "Maadi",
    "interviewType": "Online (Mon–Fri)",
    "interviewDays": "Mon–Fri",
    "shift": "Rotational",
    "transportation": "Provided",
    "insurance": "Social & Medical",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Name, Phone, Experience, Language Level",
    "commission": "After 1 Month",
    "notes": ""
  },
  {
    "id": 49,
    "company": "Konecta",
    "publicCompany": "Global Multichannel Customer Experience Partner",
    "language": "Dutch",
    "status": "on hold",
    "title": "Chat Support",
    "salary": "55000.0",
    "salaryDisplay": "EGP 55,000",
    "salaryMin": 55000.0,
    "salaryMax": 55000.0,
    "education": "Graduates Only",
    "maxAge": "Any",
    "gender": "Any",
    "experience": "Required (CS)",
    "location": "New Cairo",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "Not Provided (last shift ends 12AM)",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Sending Date, Name, Phone, ID, Email",
    "commission": "After 1 Month",
    "notes": "WFH after probation based on performance. No transport."
  },
  {
    "id": 50,
    "company": "Konecta",
    "publicCompany": "Global Multichannel Customer Experience Partner",
    "language": "German",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "34000.0",
    "salaryDisplay": "EGP 34,000",
    "salaryMin": 34000.0,
    "salaryMax": 34000.0,
    "education": "Graduates Only",
    "maxAge": "Any",
    "gender": "Any",
    "experience": "Required (CS)",
    "location": "New Cairo",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "Allowance (3K)",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Sending Date, Name, Phone, ID, Email",
    "commission": "After 1 Month",
    "notes": ""
  },
  {
    "id": 51,
    "company": "Konecta",
    "publicCompany": "Global Multichannel Customer Experience Partner",
    "language": "French",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "25000.0",
    "salaryDisplay": "EGP 25,000",
    "salaryMin": 25000.0,
    "salaryMax": 25000.0,
    "education": "Graduates Only",
    "maxAge": "Any",
    "gender": "Any",
    "experience": "Required (CS)",
    "location": "New Cairo",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "Allowance (3K)",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Sending Date, Name, Phone, ID, Email",
    "commission": "After 1 Month",
    "notes": ""
  },
  {
    "id": 52,
    "company": "O4U",
    "publicCompany": "Premium Customer Operations Hub",
    "language": "English",
    "status": "on hold",
    "title": "Telesales – UK Account",
    "salary": "16000.0",
    "salaryDisplay": "EGP 16,000",
    "salaryMin": 16000.0,
    "salaryMax": 16000.0,
    "education": "Grads, Undergrads & Dropouts",
    "maxAge": "Any",
    "gender": "Any",
    "experience": "Not Required",
    "location": "Maadi",
    "interviewType": "On-Site (Mon–Fri 12:30–5PM)",
    "interviewDays": "Mon–Fri 12:30PM–5PM",
    "shift": "Fixed (Mon–Thu 12:15PM–8:30PM / Fri 11AM–7:30PM)",
    "transportation": "Not Specified",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "Yes",
    "candidateInfo": "Name, Phone, Education, Experience",
    "commission": "After 1 Month",
    "notes": "Sat & Sun off. Send voice note in English to apply."
  },
  {
    "id": 53,
    "company": "Octpus",
    "publicCompany": "Creative Solutions & Outsourcing Agency",
    "language": "English B1",
    "status": "on hold",
    "title": "Customer Service Representative (English Account)",
    "salary": "7,000 EGP (80% Basic + 20% KPIs)",
    "salaryDisplay": "EGP 7,000",
    "salaryMin": 7000.0,
    "salaryMax": 7000.0,
    "education": "Graduates only",
    "maxAge": "Maximum 40 years old",
    "gender": "Any",
    "experience": "No experience needed",
    "location": "Nasr City, Cairo (Brightskies office, Al Wafaa Wal Amal, Nasr City Free Zone)",
    "interviewType": "Onsite Interview",
    "interviewDays": "Wednesday, from 12:00 PM to 4:00 PM",
    "shift": "Rotational Shifts",
    "transportation": "Transportation Allowance: 2,000 EGP",
    "insurance": "not specified",
    "workType": "On-Site",
    "foreigners": "no",
    "candidateInfo": "",
    "commission": "TBD",
    "notes": ""
  },
  {
    "id": 54,
    "company": "Octpus",
    "publicCompany": "Creative Solutions & Outsourcing Agency",
    "language": "English B1+/B2",
    "status": "on hold",
    "title": "Customer Service Representative (English Account)",
    "salary": "Net (14,000 EGP Net + 2,000 EGP Transportation Allowance)",
    "salaryDisplay": "EGP 14,000",
    "salaryMin": 14000.0,
    "salaryMax": 14000.0,
    "education": "Graduates only",
    "maxAge": "Maximum 40 years old",
    "gender": "Any",
    "experience": "No experience needed",
    "location": "Nasr City, Cairo (Brightskies office, Al Wafaa Wal Amal, Nasr City Free Zone)",
    "interviewType": "Onsite Interview",
    "interviewDays": "Wednesday, from 12:00 PM to 4:00 PM",
    "shift": "Rotational Shifts",
    "transportation": "Transportation Allowance: 2,000 EGP",
    "insurance": "not specified",
    "workType": "On-Site",
    "foreigners": "no",
    "candidateInfo": "",
    "commission": "TBD",
    "notes": ""
  },
  {
    "id": 55,
    "company": "TP",
    "publicCompany": "Global Customer Experience Giant",
    "language": "Dutch",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "51000.0",
    "salaryDisplay": "EGP 51,000",
    "salaryMin": 51000.0,
    "salaryMax": 51000.0,
    "education": "Grads & Undergrads",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required",
    "location": "5th Settlement, New Cairo",
    "interviewType": "On-Site @ TP Katamya",
    "interviewDays": "Daily",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "Experience is a MUST. KPIs in EUR"
  },
  {
    "id": 56,
    "company": "TP",
    "publicCompany": "Global Customer Experience Giant",
    "language": "German",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "35000.0",
    "salaryDisplay": "EGP 35,000",
    "salaryMin": 35000.0,
    "salaryMax": 35000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "5th Settlement, New Cairo",
    "interviewType": "On-Site @ TP Plaza",
    "interviewDays": "Daily",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "KPIs in EUR, highest paying EUR lang"
  },
  {
    "id": 57,
    "company": "TP",
    "publicCompany": "Global Customer Experience Giant",
    "language": "Spanish",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "26000.0",
    "salaryDisplay": "EGP 26,000",
    "salaryMin": 26000.0,
    "salaryMax": 26000.0,
    "education": "Grads & Undergrads",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "5th Settlement, New Cairo",
    "interviewType": "On-Site @ TP Katamya",
    "interviewDays": "Daily",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "KPIs in EUR"
  },
  {
    "id": 58,
    "company": "TP",
    "publicCompany": "Global Customer Experience Giant",
    "language": "French",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "25000.0",
    "salaryDisplay": "EGP 25,000",
    "salaryMin": 25000.0,
    "salaryMax": 25000.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "5th Settlement, New Cairo",
    "interviewType": "On-Site @ TP Katamya",
    "interviewDays": "Daily",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "KPIs in EUR"
  },
  {
    "id": 59,
    "company": "TP",
    "publicCompany": "Global Customer Experience Giant",
    "language": "Italian",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "24000.0",
    "salaryDisplay": "EGP 24,000",
    "salaryMin": 24000.0,
    "salaryMax": 24000.0,
    "education": "Grads & Undergrads",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "5th Settlement, New Cairo",
    "interviewType": "On-Site @ TP Katamya",
    "interviewDays": "Daily",
    "shift": "Rotational / Night",
    "transportation": "Provided",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email, Language",
    "commission": "After 1 Month",
    "notes": "KPIs in EUR"
  },
  {
    "id": 60,
    "company": "VXI",
    "publicCompany": "Leading Customer Service & Tech Support Provider",
    "language": "English",
    "status": "on hold",
    "title": "Customer Service",
    "salary": "19000.0",
    "salaryDisplay": "EGP 19,000",
    "salaryMin": 19000.0,
    "salaryMax": 19000.0,
    "education": "Grads & Undergrads",
    "maxAge": "50.0",
    "gender": "Any",
    "experience": "Not Required",
    "location": "City Stars, Nasr City",
    "interviewType": "Online Interview",
    "interviewDays": "TBD",
    "shift": "Night / Overnight (3PM–7AM)",
    "transportation": "Provided (Stadium Metro, Nasr City, 5th Settlement)",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Sending Date, Name, Phone, ID, Email",
    "commission": "After 1 Month",
    "notes": "Overnight allowance extra. Door-to-door females after 11PM"
  },
  {
    "id": 61,
    "company": "Vodafone",
    "publicCompany": "Global Telecommunications Leader",
    "language": "English",
    "status": "on hold",
    "title": "Customer Service – High Value",
    "salary": "11600.0",
    "salaryDisplay": "EGP 11,600",
    "salaryMin": 11600.0,
    "salaryMax": 11600.0,
    "education": "Graduates Only",
    "maxAge": "29.0",
    "gender": "Males Only",
    "experience": "Not Required",
    "location": "Zahraa Maadi",
    "interviewType": "Language filter via ACM, then VF online interview",
    "interviewDays": "TBD",
    "shift": "Rotational",
    "transportation": "To Metro Station",
    "insurance": "Medical & Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Name, Phone, Alt Phone, Email",
    "commission": "After 4 Days Training",
    "notes": "On Hold. Bonus every 3 months. VF phone line benefits."
  },
  {
    "id": 62,
    "company": "eClerx",
    "publicCompany": "Premium Business Operations & IT Partner",
    "language": "English",
    "status": "on hold",
    "title": "Customer Care – US Voice / Sales & Upselling",
    "salary": "17851.0",
    "salaryDisplay": "EGP 17,851",
    "salaryMin": 17851.0,
    "salaryMax": 17851.0,
    "education": "Graduates Only",
    "maxAge": "45.0",
    "gender": "Any",
    "experience": "Required (CS & Sales)",
    "location": "Maadi Tech Park",
    "interviewType": "On-Site (Sun–Thu 12PM–4:45PM)",
    "interviewDays": "Sun–Thu, slots every 15 mins",
    "shift": "Rotational (incl. evenings/weekends)",
    "transportation": "Not Specified",
    "insurance": "Social",
    "workType": "On-Site",
    "foreigners": "No",
    "candidateInfo": "Interview Date, Name, Phone, Email",
    "commission": "After 1 Month",
    "notes": "Performance bonus up to 48K annually. 2 on-site assessments (~1.5hrs each)."
  }
];
